# ./scripts/fetch_nse_financial_results.py --top 50 --source webpage
./scripts/xbrl_eod.py --symbol   HDFCBANK 
 ./scripts/xbrl_eod.py --symbol   BHARTIARTL  
./scripts/xbrl_eod.py --symbol   TCS  
./scripts/xbrl_eod.py --symbol   ICICIBANK  
./scripts/xbrl_eod.py --symbol   SBIN  
./scripts/xbrl_eod.py --symbol   BAJFINANCE  
./scripts/xbrl_eod.py --symbol   INFY  
./scripts/xbrl_eod.py --symbol   HINDUNILVR  
./scripts/xbrl_eod.py --symbol   LICI  
./scripts/xbrl_eod.py --symbol   LT  
./scripts/xbrl_eod.py --symbol   ITC 
./scripts/xbrl_eod.py --symbol   MARUTI  
./scripts/xbrl_eod.py --symbol   M&M  
./scripts/xbrl_eod.py --symbol   KOTAKBANK  
./scripts/xbrl_eod.py --symbol   HCLTECH  
./scripts/xbrl_eod.py --symbol   SUNPHARMA  
./scripts/xbrl_eod.py --symbol   AXISBANK  
./scripts/xbrl_eod.py --symbol   ULTRACEMCO  
./scripts/xbrl_eod.py --symbol   BAJAJFINSV  
./scripts/xbrl_eod.py --symbol   TITAN  
./scripts/xbrl_eod.py --symbol   NTPC  
./scripts/xbrl_eod.py --symbol   ADANIPOWER 
./scripts/xbrl_eod.py --symbol   HAL  
./scripts/xbrl_eod.py --symbol   ONGC  
./scripts/xbrl_eod.py --symbol   ADANIPORTS  
./scripts/xbrl_eod.py --symbol   BEL  
./scripts/xbrl_eod.py --symbol   ETERNAL  
./scripts/xbrl_eod.py --symbol   ADANIENT  
./scripts/xbrl_eod.py --symbol   JSWSTEEL  
./scripts/xbrl_eod.py --symbol   DMART  
./scripts/xbrl_eod.py --symbol   POWERGRID  
./scripts/xbrl_eod.py --symbol   WIPRO  
./scripts/xbrl_eod.py --symbol   BAJAJ-AUTO 
 ./scripts/xbrl_eod.py --symbol   NESTLEIND  
./scripts/xbrl_eod.py --symbol   COALINDIA  
./scripts/xbrl_eod.py --symbol   ASIANPAINT 
./scripts/xbrl_eod.py --symbol   INDIGO 
./scripts/xbrl_eod.py --symbol   TATASTEEL  
./scripts/xbrl_eod.py --symbol   IOC  
./scripts/xbrl_eod.py --symbol   HINDZINC  
./scripts/xbrl_eod.py --symbol   JIOFIN  
./scripts/xbrl_eod.py --symbol   VEDL  
./scripts/xbrl_eod.py --symbol   GRASIM  
./scripts/xbrl_eod.py --symbol   DLF  
./scripts/xbrl_eod.py --symbol   EICHERMOT  
./scripts/xbrl_eod.py --symbol   SBILIFE  
./scripts/xbrl_eod.py --symbol   HINDALCO  
./scripts/xbrl_eod.py --symbol   HYUNDAI  
./scripts/xbrl_eod.py --symbol   DIVISLAB